[component]
array_structures = [ "content_blocks" ]
label = "Call to action"
description = "Call to action block with a button"
icon = "call_to_action"
tags = ["Text"]

[props]
heading = "This is a title"
lower_text_html = "This is a description"
button_label = "Button name"
button_url = "Button url"
