[component]
array_structures = [ "content_blocks" ]
label = "Latest Blog"
description = "List of Latest Blog items"
icon = "fiber_new"
tags = ["Data"]

[props]
title = ""
show_post_tags = true
show_post_date = true
