[component]
array_structures = [ "content_blocks" ]
label = "Icon section"
description = "Title on one side and content on the other with icons attached to it"
icon = "ballot"
tags = ["Text"]

[props]
caption_title = "This is a caption title"
main_title = "This is a main title"
icon_layout.select = ["left", "right"]
icon_layout.default = "right"

[[props.items]]
icon_image.default = "" #:
icon_image_alt.default = "Icon image"  #: Provide the alternative text for the image
title = "This is a title"
description_html = "This is a description"
button_label = "Button name"
button_url = "Button url"
