[component]
array_structures = [ "content_blocks" ]
label = "Testimonial"
description = "Image with some quotes or review"
icon = "format_quote"
tags = ["Text"]

[props]
layout.select = ["image_left", "image_right"]  #: Select the layout for the image.
layout.default = "image_left"  #: Default layout for the image

caption_title = "This is a caption title"
main_title = "This is a main title"
image.default = ""  #: Select testimonial image
image_alt.default = "Testimonial image"  #: Provide the alternative text for the image
content_heading = "This is a title"
content_html = "This is a description"
author_name = "Author name"
author_designation = "Designation"
