[component]
array_structures = [ "content_blocks" ]
label = "Testimonial"
description = "Image with some quotes or review"
icon = "format_quote"
tags = ["Text"]

[props]
testimonial_layout.select = ["image_left", "image_right"]  #: Select the layout for the image.
testimonial_layout.default = "image_left"  #: Default layout for the image

testimonial_caption_title = "This is a caption title"
testimonial_main_title = "This is a main title"
testimonial_image.default = ""  #: Select testimonial image
testimonial_image_alt.default = "Testimonial image"  #: Provide the alternative text for the image
testimonial_title = "This is a title"
testimonial_description_html = "This is a description"
testimonial_author_name = "Author name"
testimonial_author_designation = "Designation"
