source "https://rubygems.org"

gem 'sass-embedded', '~> 1.60'  # Add this line for compatibility

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.0.1"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-sass-converter', :git => "https://github.com/CloudCannon/jekyll-sass-converter.git"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-local-assign'
  gem 'jekyll-include-cache'
end
