[component]
array_structures = [ "content_blocks" ]
label = "Feature Blog Hero Content"
description = "These module's content comes from the blog, Image on one side and content on the other with a call to action button"
icon = "menu_book"
tags = ["Data"]

[props]
layout.select = ["image_left", "image_right"]  #: Select the layout for the image
layout.default = "image_right"  #: Default value forr the image

component_width.select = ["fullwidth", "normal"]  #: Select the type for the feature blog
component_width.default = "normal"  #: Default type for the feature blog

mobile_image_order.select = ["bottom", "top"]  #: Select the image order mobile
mobile_image_order.default = "bottom"  #: Default image order for mobile

vertical_alignment.select = ["top", "center", "bottom"]  #: Select the vertical alignment for feature blog
vertical_alignment.default = "top"  #: Default vertical alignment for feature blog

display_image = true
display_title = true
display_description = true
