[component]
array_structures = [ "content_blocks" ]
label = "Contact"
description = "Contact form, address, email, number and map iframe"
icon = "location_on"
tags = ["Form"]

[props]
address = ""  #: Enter the contact address
email = ""  #: Enter the contact Email address
phone = ""  #: Enter the contact phone number
map-iframe = ""  #: Enter the google iframe src

layout.select = ["map_left", "map_right"]  #: Select the contact layout for the map.
layout.default = "map_right"  #: Default contact layout for the map.