[component]
array_structures = [ "content_blocks" ]
label = "Trending Blog"
description = "List of Trending Blog items"
icon = "trending_up"
tags = ["Data"]

[props]
title = ""  #: Enter trending blog title
posts_to_show_number = "3"  #: Enter the number of posts
show_post_tags = true
show_post_date = true
