[component]
array_structures = [ "content_blocks" ]
label = "Info section"
description = "Title and caption title above with icon, description and a call to action below"
icon = "view_stream"
tags = ["Text"]

[props]
info_caption_title = "This is a caption title"
info_main_title = "This is a main title"
info_main_description_html = "This is a description"
info_section_number_of_column.select = ["2", "3", "4"]  #: Select the number of column for info section


[[props.info-section]]
info_section_alignment.select = ["left", "center", "right"]  #: Select the alignment for info section
info_image.default = ""  #: Select the info image
info_image_alt.default = "Icon image"  #: Provide the alternative text for the image
info_title = "This is a title"
info_description_html = "This is a description"
info_button_name = "Button name"
info_button_url = "Button url"
