[component]
array_structures = [ "content_blocks" ]
label = "Team List"
description = "List of team-list collection items"
icon = "groups"
tags = ["Data"]

[props]
alignment.select = ["left", "center", "right"]  #: Select the alignment for team list
caption_title = ""
main_title = ""
description_html = ""
columns.select = ["2", "3", "4"]
people_to_display_number = 6
show_button = true
